# Generated by Django 2.0 on 2020-04-12 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='任务名称')),
                ('status', models.PositiveSmallIntegerField(choices=[(0, '待接收'), (1, '已接收')], default=0, verbose_name='任务状态')),
            ],
        ),
        migrations.CreateModel(
            name='TaskList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True, verbose_name='任务清单名称')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='lid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task', to='tasklist.TaskList', verbose_name='任务所属清单'),
        ),
    ]
