# Generated by Django 2.2.12 on 2020-04-13 02:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasklist', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='lid',
            new_name='tl',
        ),
    ]
